version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile-web
    container_name: flask-twitter
    tty: true
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"