version: 2.1
orbs:
  heroku-container: pbrisbin/heroku-container@1.0.0
  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2

jobs:
  build_and_deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - cloudrun/init
      - cloudrun/build:
          tag: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
      - cloudrun/deploy:
          image: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
          platform: managed
          region: asia-northeast1-a
          service-name: flask-twitter
          unauthenticated: true

workflows:
  build_and_release:
    jobs:
      - heroku-container/push-and-release:
          app-name: twitter-techtech
          # masterブランチへのpushでのみ反応
          filters:
                branches:
                    only:
                    - staging
  build_and_deploy_to_managed_workflow:
    jobs:
      - build_and_deploy:
          filters:
            branches:
                only:
                - master
