version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
  aws-ecs: circleci/aws-ecs@0.0.10
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: 'practice'
          region: AWS_REGION
          tag: '${CIRCLE_SHA1}'
          filters:    # ここを追加
                branches:
                    only:
                    - master
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: '${MY_APP_PREFIX}-service'
          cluster-name: 'flask-twitter'
          service-name: 'flask-twitter-FrontendService-TEco3qsgE4mo'
          container-image-name-updates: 'container=practice-service,tag=${CIRCLE_SHA1}'
          filters:    # ここを追加
                branches:
                    only:
                    - master