version: 2.1
orbs:
  heroku-container: pbrisbin/heroku-container@1.0.0
workflows:
  build_and_release:
    jobs:
<<<<<<< HEAD
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: 'practice'
          region: AWS_REGION
          tag: '${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: '${MY_APP_PREFIX}-service'
          cluster-name: 'flask-twitter'
          service-name: 'flask-twitter-FrontendService-TEco3qsgE4mo'
          container-image-name-updates: 'container=practice-service,tag=${CIRCLE_SHA1}'
=======
      - heroku-container/push-and-release:
          app-name: twitter-techtech
          # masterブランチへのpushでのみ反応
          filters:
                branches:
                    only:
                    - master
>>>>>>> 69271c65aca0ce18fd857a6b7061a535801338d6
