version: 2.1
orbs:
  deploy-to-heroku: betterdoc/deploy-to-heroku@4.2.0
workflows:
  docker-build-release:
    jobs:
      - deploy-to-heroku/docker-build-release:
        #
          app-name: twitter-techtech
        # masterブランチへのpushでのみ反応
          filters:
                branches:
                    only:
                    - master
